# Site settings
title: InProgress
email: kirbieskirbies@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An attempt to organize and log my projects
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://kirbieskirbies.github.io. # the base hostname & protocol for your site
twitter_username: ""
github_username:  kirbieskirbies


# Build settings
markdown: kramdown
kramdown:
  input: GFM

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
  - jekyll-archives

paginate:  2
paginate_path: "/page/:num"

jekyll-archives:
  enabled:
    - year
    - month
    - day
  layouts:
    year: year-archive
    month: month-archive
    day: day-archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'